package org.phoenixgriffon.JobIsep;
// Generated 2 mai 2017 15:53:06 by Hibernate Tools 5.2.1.Final

/**
 * EffectueStage generated by hbm2java
 */
public class EffectueStage implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Utilisateur id_utilisateur;
	private Stage id_stage;

	public EffectueStage() {
	}

	public EffectueStage(Stage stage, Utilisateur utilisateur) {
		this.id_utilisateur = utilisateur;
		this.id_stage = stage;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Utilisateur getId_utilisateur() {
		return id_utilisateur;
	}

	public void setId_utilisateur(Utilisateur id_utilisateur) {
		this.id_utilisateur = id_utilisateur;
	}

	public Stage getId_stage() {
		return id_stage;
	}

	public void setId_stage(Stage id_stage) {
		this.id_stage = id_stage;
	}
}
