package org.phoenixgriffon.JobIsep;
// Generated 2 mai 2017 15:53:06 by Hibernate Tools 5.2.1.Final

/**
 * Parcours generated by hbm2java
 */
public class Parcours implements java.io.Serializable {

	private Integer id;
	private Utilisateur utilisateur;
	private String libelle;

	public Parcours() {
	}

	public Parcours(Utilisateur utilisateur, String libelle) {
		this.utilisateur = utilisateur;
		this.libelle = libelle;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

}
