package org.phoenixgriffon.JobIsep;
// Generated 2 mai 2017 15:53:06 by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * StatutUtilisateur generated by hbm2java
 */
public class StatutUtilisateur implements java.io.Serializable {

	private Integer id;
	private String libelle;
	private Set<Utilisateur> utilisateurs = new HashSet<Utilisateur>(0);

	public StatutUtilisateur() {
	}

	public StatutUtilisateur(String libelle) {
		this.libelle = libelle;
	}
	
	public StatutUtilisateur(Integer id,String libelle) {
		this.id = id;
		this.libelle = libelle;
	}

	public StatutUtilisateur(String libelle, Set<Utilisateur> utilisateurs) {
		this.libelle = libelle;
		this.utilisateurs = utilisateurs;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public Set<Utilisateur> getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Set<Utilisateur> utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

}
