package org.phoenixgriffon.JobIsep;
// Generated 2 mai 2017 15:53:06 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Utilisateur generated by hbm2java
 */
public class Utilisateur implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String prenom;
	private String nom;
	private Date dateNaissance;
	private String identifiant;
	private String motdepasse;
	private StatutUtilisateur statutUtilisateur;
	private Set<Offre> offres = new HashSet<Offre>(0);
	private Set<EffectueStage> effectueStages = new HashSet<EffectueStage>(0);
	private Set<Parcours> parcourses = new HashSet<Parcours>(0);
	private Set<ValideStage> valideStages = new HashSet<ValideStage>(0);

	public Utilisateur() {
	}

	public Utilisateur(StatutUtilisateur statutUtilisateur, String prenom, String nom, Date dateNaissance,
			String identifiant, String motdepasse) {
		this.statutUtilisateur = statutUtilisateur;
		this.prenom = prenom;
		this.nom = nom;
		this.dateNaissance = dateNaissance;
		this.identifiant = identifiant;
		this.motdepasse = motdepasse;
	}

	public Utilisateur(StatutUtilisateur statutUtilisateur, String prenom, String nom, Date dateNaissance,
			String identifiant, String motdepasse, Set<Offre> offres, Set<EffectueStage> effectueStages,
			Set<Parcours> parcourses, Set<ValideStage> valideStages) {
		this.statutUtilisateur = statutUtilisateur;
		this.prenom = prenom;
		this.nom = nom;
		this.dateNaissance = dateNaissance;
		this.identifiant = identifiant;
		this.motdepasse = motdepasse;
		this.offres = offres;
		this.effectueStages = effectueStages;
		this.parcourses = parcourses;
		this.valideStages = valideStages;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public StatutUtilisateur getStatutUtilisateur() {
		return this.statutUtilisateur;
	}

	public void setStatutUtilisateur(StatutUtilisateur statutUtilisateur) {
		this.statutUtilisateur = statutUtilisateur;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public Date getDateNaissance() {
		return this.dateNaissance;
	}

	public void setDateNaissance(Date dateNaissance) {
		this.dateNaissance = dateNaissance;
	}

	public String getIdentifiant() {
		return this.identifiant;
	}

	public void setIdentifiant(String identifiant) {
		this.identifiant = identifiant;
	}

	public String getMotdepasse() {
		return this.motdepasse;
	}

	public void setMotdepasse(String motdepasse) {
		this.motdepasse = motdepasse;
	}

	public Set<Offre> getOffres() {
		return this.offres;
	}

	public void setOffres(Set<Offre> offres) {
		this.offres = offres;
	}

	public Set<EffectueStage> getEffectueStages() {
		return this.effectueStages;
	}

	public void setEffectueStages(Set<EffectueStage> effectueStages) {
		this.effectueStages = effectueStages;
	}

	public Set<Parcours> getParcourses() {
		return this.parcourses;
	}

	public void setParcourses(Set<Parcours> parcourses) {
		this.parcourses = parcourses;
	}

	public Set<ValideStage> getValideStages() {
		return this.valideStages;
	}

	public void setValideStages(Set<ValideStage> valideStages) {
		this.valideStages = valideStages;
	}

}
