package org.phoenixgriffon.JobIsep;
// Generated 2 mai 2017 15:53:06 by Hibernate Tools 5.2.1.Final

/**
 * Entreprise generated by hbm2java
 */
public class Entreprise implements java.io.Serializable {

	private Integer id;
	private String nom;
	private String siret;
	private String codeApe;
	private String adresseSiege;
	private String villeSiege;
	private String codePostalSiege;
	private String telephoneSiege;

	public Entreprise() {
	}

	public Entreprise(String nom, String siret, String codeApe, String adresseSiege, String villeSiege,
			String codePostalSiege, String telephoneSiege) {
		this.nom = nom;
		this.siret = siret;
		this.codeApe = codeApe;
		this.adresseSiege = adresseSiege;
		this.villeSiege = villeSiege;
		this.codePostalSiege = codePostalSiege;
		this.telephoneSiege = telephoneSiege;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getSiret() {
		return this.siret;
	}

	public void setSiret(String siret) {
		this.siret = siret;
	}

	public String getCodeApe() {
		return this.codeApe;
	}

	public void setCodeApe(String codeApe) {
		this.codeApe = codeApe;
	}

	public String getAdresseSiege() {
		return this.adresseSiege;
	}

	public void setAdresseSiege(String adresseSiege) {
		this.adresseSiege = adresseSiege;
	}

	public String getVilleSiege() {
		return this.villeSiege;
	}

	public void setVilleSiege(String villeSiege) {
		this.villeSiege = villeSiege;
	}

	public String getCodePostalSiege() {
		return this.codePostalSiege;
	}

	public void setCodePostalSiege(String codePostalSiege) {
		this.codePostalSiege = codePostalSiege;
	}

	public String getTelephoneSiege() {
		return this.telephoneSiege;
	}

	public void setTelephoneSiege(String telephoneSiege) {
		this.telephoneSiege = telephoneSiege;
	}

}
